name: Github Searcher CI

on:
  push:
    branches: ["main"]

jobs:
  CI:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: yarn install
      - name: Jest tests & lint
        run: yarn ci
      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          coverage-summary-path: ./coverage/coverage-summary.json
          branches: main
      - name: build docker image
        run: docker build -t github-searcher .
